/*
 * Revised character logic for the isometric hex game prototype.
 *
 * In the original version a small yellow triangle was overlaid on the
 * character to indicate which neighbouring hex the unit was facing.  That
 * approach limited the player sprite to pointing only left or right while
 * the indicator communicated the true direction.  This script removes
 * the triangle entirely and instead swaps out the sprite itself for one of
 * six directional images.  Each of the six axial directions in a pointy‑top
 * hex grid is mapped to a pre‑cropped frame extracted from the original
 * sprite sheet.  See game/style.css for the sizing rules applied to
 * `.character`.
 */

const GRID_SIZE = 5;
const SIZE = 50; // hex radius
const game = document.getElementById('game');
let tiles = [];
let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;

// Direction vectors for pointy‑top axial coordinates.  Each entry
// corresponds to one of the six neighbours.  The labels here map
// diagonal directions rather than pure vertical moves.  The six
// directions are: left, left‑up, right‑up, right, right‑down and
// left‑down.  Note that the vectors themselves have not changed –
// only their descriptive names have been updated.
const directionVectors = {
  left:       { dq: -1, dr: 0 },      // west
  'left-up':  { dq: 0,  dr: -1 },     // northwest
  'right-up': { dq: 1,  dr: -1 },     // northeast
  right:      { dq: 1,  dr: 0 },      // east
  'right-down': { dq: 0,  dr: 1 },    // southeast
  'left-down': { dq: -1, dr: 1 }      // southwest
};

// Map each direction to a specific sprite.  These images were
// generated by cropping a sprite sheet (see player_soldier.png) and
// flipping where appropriate.  Having dedicated sprites for each
// direction eliminates the need for a separate indicator overlay.
// Map each direction to the appropriate sprite.  The mapping below
// takes into account the camera's position relative to the unit.  For
// directions on the left side of the screen (west and north‑west) the
// player's right side is visible to the camera, so we use the right‑side
// sprites.  Conversely, for directions on the right side of the screen
// (east and north‑east) the player's left side is visible, so we use
// the left‑side sprites.  Likewise, the down‑facing directions pick
// between front‑left and front‑right depending on which side is more
// visible to the camera.  This swap corrects the earlier off‑by‑one
// orientation reported by the user.
const spriteMap = {
  // Facing west: show the player's right side
  right:         'player_right.png',
  // Facing north‑west: show the player's back‑right
  'left-up':    'player_right_up.png',
  // Facing north‑east: show the player's back‑left
  'right-up':   'player_left_up.png',
  // Facing east: show the player's left side
  left:        'player_left.png',
  // Facing south‑east: show the player's front‑left
  'left-down': 'player_left_down.png',
  // Facing south‑west: show the player's front‑right
  'right-down':  'player_right_down.png'
  ,
  // Pure up and down orientations used when the camera rotates the
  // world directions to align vertically.
  up:           'player_up.png',
  down:         'player_down.png'
};

/**
 * Convert axial (q, r) coordinates to pixel coordinates.  The formulas
 * here assume pointy‑top hexes and produce coordinates in a 2D plane.
 *
 * @param {number} q Axial q coordinate
 * @param {number} r Axial r coordinate
 * @returns {{x:number,y:number}} Pixel coordinates
 */
function axialToPixel(q, r) {
  const x = SIZE * Math.sqrt(3) * (q + r / 2);
  const y = SIZE * 1.5 * r;
  return { x, y };
}

// Identity function for this pseudo‑3D projection.  It is kept here
// for clarity and potential future use if an actual isometric transform
// becomes necessary.
function iso(x, y) {
  return { x, y };
}

// Precompute tile positions and bounding box extents.
for (let q = 0; q < GRID_SIZE; q++) {
  for (let r = 0; r < GRID_SIZE; r++) {
    const { x, y } = axialToPixel(q, r);
    const p = iso(x, y);
    minX = Math.min(minX, p.x);
    minY = Math.min(minY, p.y);
    maxX = Math.max(maxX, p.x);
    maxY = Math.max(maxY, p.y);
    tiles.push({ q, r, x: p.x, y: p.y });
  }
}

// Camera angle in degrees.  This controls how the world is rotated
// when drawn.  It is initialised to 0 (no rotation) and can be
// incremented or decremented by pressing E or Q on the keyboard.  The
// value wraps around 360 degrees.
let cameraAngle = 0;

// Current offsets for positioning tiles and the character.  These
// values are recalculated whenever the camera rotates.  They shift
// the rotated coordinates so that the grid remains centred within
// the #game container.
let currentOffsetX = 0;
let currentOffsetY = 0;

// Basis vectors for the axial coordinate system in pixel space when
// the camera is unrotated.  In a pointy‑top hex grid the q axis is
// horizontal (pointing east) and the r axis points down and to the
// right.
const basisQ = { x: SIZE * Math.sqrt(3), y: 0 };
const basisR = { x: SIZE * Math.sqrt(3) / 2, y: SIZE * 1.5 };

// Rotated basis vectors for the current camera angle.  These are
// updated in updateAllTiles() and used by updateCharacter() to
// position the character.  They are objects with x and y
// properties.
let rotBasisQ = { x: basisQ.x, y: basisQ.y };
let rotBasisR = { x: basisR.x, y: basisR.y };

// Rotate a point (x, y) by the given angle (in degrees) around the
// origin.  Positive angles rotate counter‑clockwise.
function rotatePoint(x, y, angleDeg) {
  const rad = angleDeg * Math.PI / 180;
  const cos = Math.cos(rad);
  const sin = Math.sin(rad);
  return {
    x: x * cos - y * sin,
    y: x * sin + y * cos
  };
}

// Update all tiles' positions based on the current camera angle.
// This function rotates the precomputed world positions and then
// centres the grid by computing a bounding box.  It also stores
// currentOffsetX/Y for use by the character positioning.
function updateAllTiles() {
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  // Compute rotated basis vectors for the current camera angle.  These
  // define how the axial q and r axes map into pixel space.
  rotBasisQ = rotatePoint(basisQ.x, basisQ.y, cameraAngle);
  rotBasisR = rotatePoint(basisR.x, basisR.y, cameraAngle);
  // First compute rotated coordinates and bounding box
  tiles.forEach(t => {
    // Use the rotated basis to position this tile
    const x = rotBasisQ.x * t.q + rotBasisR.x * t.r;
    const y = rotBasisQ.y * t.q + rotBasisR.y * t.r;
    t.rotX = x;
    t.rotY = y;
    minX = Math.min(minX, x);
    minY = Math.min(minY, y);
    maxX = Math.max(maxX, x);
    maxY = Math.max(maxY, y);
  });
  // Compute offsets so that the rotated grid is centred in the game
  currentOffsetX = (game.offsetWidth - (maxX - minX)) / 2 - minX;
  currentOffsetY = (game.offsetHeight - (maxY - minY)) / 2 - minY;
  // Apply positions to tile DOM elements
  tiles.forEach(t => {
    t.element.style.left = (t.rotX + currentOffsetX) + 'px';
    t.element.style.top  = (t.rotY + currentOffsetY) + 'px';
    // Rotate the tile shape itself so that it aligns with the rotated
    // grid.  Without this rotation the hex appears skewed when the
    // camera turns.  The translate(-50%,-50%) centres the element
    // about its coordinate, so applying rotation afterwards rotates
    // around its centre.
    t.element.style.transform = `translate(-50%, -50%) rotate(${cameraAngle}deg)`;
  });
}

/**
 * Determine which sprite orientation should be displayed for a
 * character facing a particular world direction given the current
 * camera angle.  The world direction is provided as a string key
 * corresponding to the keys in directionVectors.  The function
 * computes the pixel vector for that direction, rotates it by the
 * camera angle, and then classifies the resulting angle into one of
 * the eight orientation labels: 'right', 'right-down', 'down',
 * 'left-down', 'left', 'left-up', 'up' or 'right-up'.  When the
 * rotated vector is close to vertical (within 30 degrees of
 * straight up or down) the 'up' or 'down' sprites are chosen.
 * Otherwise the nearest of the six side directions is selected.
 *
 * @param {string} facing The world direction the character is facing
 * @returns {string} The display orientation name
 */
function getDisplayDirection(facing) {
  const vec = directionVectors[facing];
  // Convert the axial direction into pixel space (unrotated)
  const base = axialToPixel(vec.dq, vec.dr);
  // Rotate by the camera angle to see how it appears on screen
  const rot = rotatePoint(base.x, base.y, cameraAngle);
  const rx = rot.x;
  const ry = rot.y;
  // Classify the angle of the rotated vector into one of twelve 30°
  // sectors.  We then map pairs of adjacent sectors to the six
  // diagonal directions or to up/down for the sectors around ±90°.
  const angle = Math.atan2(ry, rx);
  // Quantise the angle to the nearest 30°.  This yields an integer
  // index where 0 corresponds to 0°, 1 to 30°, 2 to 60°, etc.  Values
  // wrap around at ±180°.
  let index = Math.round(angle / (Math.PI / 6));
  // Normalise index to range [-6, 6]
  if (index > 6) index -= 12;
  if (index < -6) index += 12;
      // Map the quantised sector index to one of our eight display
      // orientations.  Each case (or group of cases) corresponds to
      // one of the major hex directions plus the vertical up/down.
      switch (index) {
        case 0:
          // Angle ≈ 0° → world pointing east → player facing right
          return 'right';
        case 1:
        case 2:
          // Angles ≈ 30° or 60° → trending down and to the right
          return 'right-down';
        case 3:
          // Angle ≈ 90° → pointing straight down on screen
          return 'down';
        case 4:
        case 5:
          // Angles ≈ 120° or 150° → trending down and to the left
          return 'left-down';
        case 6:
        case -6:
          // Angle ≈ ±180° → world pointing west → player facing left
          return 'left';
        case -5:
        case -4:
          // Angles ≈ -150° or -120° → trending up and to the left
          return 'left-up';
        case -3:
          // Angle ≈ -90° → pointing straight up on screen
          return 'up';
        case -2:
        case -1:
          // Angles ≈ -60° or -30° → trending up and to the right
          return 'right-up';
        default:
          return 'right';
      }
}

// Normalise an angle in radians to the range [-π, π].  This helper
// function ensures angular differences wrap around the circle
function normaliseAngle(a) {
  while (a <= -Math.PI) a += 2 * Math.PI;
  while (a > Math.PI) a -= 2 * Math.PI;
  return a;
}

/**
 * Produce a unique key for an axial coordinate.  This helper is used
 * by the pathfinding routines to track visited nodes and to map
 * predecessors for path reconstruction.
 *
 * @param {number} q Axial q coordinate
 * @param {number} r Axial r coordinate
 * @returns {string} A unique key for the coordinate
 */
function axialKey(q, r) {
  return `${q},${r}`;
}

/**
 * Compute a path between two axial coordinates on the hex grid using
 * breadth‑first search.  All moves have equal cost so BFS yields the
 * shortest path in terms of number of steps.  If no path exists (which
 * cannot happen in this simple prototype because all tiles are
 * traversable) an empty array is returned.
 *
 * The returned path excludes the starting position; it begins with the
 * first neighbour to visit and ends with the goal coordinate.
 *
 * @param {{q:number, r:number}} start Starting axial coordinate
 * @param {{q:number, r:number}} goal Destination axial coordinate
 * @returns {Array<{q:number,r:number}>} Array of axial positions to walk through
 */
function findPath(start, goal) {
  // If the start and goal are the same, return an empty path.
  if (start.q === goal.q && start.r === goal.r) {
    return [];
  }
  const queue = [];
  const visited = new Set();
  const cameFrom = new Map();
  const startKey = axialKey(start.q, start.r);
  queue.push(start);
  visited.add(startKey);
  cameFrom.set(startKey, null);
  let found = false;
  while (queue.length > 0) {
    const current = queue.shift();
    const currentKey = axialKey(current.q, current.r);
    if (current.q === goal.q && current.r === goal.r) {
      found = true;
      break;
    }
    // Explore all neighbouring tiles using the six direction vectors
    for (const dir of Object.keys(directionVectors)) {
      const vec = directionVectors[dir];
      const nq = current.q + vec.dq;
      const nr = current.r + vec.dr;
      // Skip out‑of‑bounds coordinates
      if (nq < 0 || nq >= GRID_SIZE || nr < 0 || nr >= GRID_SIZE) {
        continue;
      }
      const neighbourKey = axialKey(nq, nr);
      if (visited.has(neighbourKey)) {
        continue;
      }
      visited.add(neighbourKey);
      queue.push({ q: nq, r: nr });
      // Record where we came from to reconstruct the path later
      cameFrom.set(neighbourKey, { q: current.q, r: current.r });
    }
  }
  // If the goal wasn't reached, return an empty path
  if (!found) {
    return [];
  }
  // Reconstruct the path by walking backwards from the goal to the start
  const path = [];
  let currentKey = axialKey(goal.q, goal.r);
  let current = { q: goal.q, r: goal.r };
  while (currentKey !== startKey) {
    path.unshift(current);
    const prev = cameFrom.get(currentKey);
    // Safety check: if prev is undefined (which shouldn't happen), abort
    if (!prev) {
      break;
    }
    current = { q: prev.q, r: prev.r };
    currentKey = axialKey(current.q, current.r);
  }
  return path;
}

/**
 * Animate the character along a given path.  Each step is delayed by a
 * small amount to allow the player to follow the movement visually.  As
 * the character moves, the direction is updated based on the movement
 * vector which in turn swaps the sprite.
 *
 * @param {Array<{q:number,r:number}>} path Sequence of axial coordinates
 * @returns {Promise<void>} Resolves when the animation has completed
 */
async function animateMovement(path) {
  for (const nextStep of path) {
    // Compute the delta between the character's current position and the
    // next step.  This delta is used to determine facing direction and
    // to update the axial coordinates.
    const dq = nextStep.q - character.q;
    const dr = nextStep.r - character.r;
    // Move the character one step in the appropriate direction
    moveCharacter(dq, dr);
    // Wait a short duration before proceeding to the next step
    await new Promise(resolve => setTimeout(resolve, 200));
  }
}

/**
 * Handle a click on a tile.  This function triggers the BFS pathfinder to
 * compute a route from the character's current location to the clicked
 * destination.  The character is then animated along this route.  If
 * the destination is the current tile or no path exists, nothing happens.
 *
 * @param {number} targetQ Axial q coordinate of the clicked tile
 * @param {number} targetR Axial r coordinate of the clicked tile
 */
function handleTileClick(targetQ, targetR) {
  const path = findPath({ q: character.q, r: character.r }, { q: targetQ, r: targetR });
  if (path.length === 0) {
    return;
  }
  animateMovement(path);
}

/**
 * Create the hex tiles inside the #game container.  Each tile is
 * absolutely positioned using the precomputed pixel coordinates and
 * registers a click handler that triggers movement.
 */
function createTiles() {
  tiles.forEach(t => {
    const div = document.createElement('div');
    div.className = 'tile';
    // Positions will be applied later by updateAllTiles()
    game.appendChild(div);
    t.element = div;
    // When the tile is clicked the character will attempt to move to that
    // location via BFS pathfinding.
    div.addEventListener('click', () => handleTileClick(t.q, t.r));
  });
}

// Character state: axial coordinates and world facing direction.  The
// facing property records which neighbour direction the character is
// looking towards in world space.  It begins at 'right'.
let character = { q: 2, r: 2, facing: 'right' };
const charDiv = document.createElement('div');
charDiv.className = 'character';
charDiv.style.left = '0px';
charDiv.style.top  = '0px';
// The background image will be set in updateCharacter() based on
// character.facing and cameraAngle, so no need to initialise here.
game.appendChild(charDiv);

/**
 * Update the character's sprite position and orientation.  The pixel
 * position is derived from the axial coordinates and adjusted by
 * offsets so that the centre of the sprite aligns with the centre of
 * the underlying hex.  The background image is looked up from
 * spriteMap based on the current direction.  A fixed translate is
 * applied to centre the 32x35 image over the tile.
 */
function updateCharacter() {
  // Compute the rotated pixel coordinates of the character using the
  // precomputed rotated basis vectors.  This ensures the grid and
  // character remain aligned after camera rotations.
  const rotX = rotBasisQ.x * character.q + rotBasisR.x * character.r;
  const rotY = rotBasisQ.y * character.q + rotBasisR.y * character.r;
  // Position the DOM element using the current offsets
  charDiv.style.left = (rotX + currentOffsetX) + 'px';
  charDiv.style.top  = (rotY + currentOffsetY) + 'px';
  // Determine which sprite orientation to use based on world facing and camera angle
  const displayDir = getDisplayDirection(character.facing);
  charDiv.style.backgroundImage = `url('${spriteMap[displayDir]}')`;
      // Store the computed display direction on the element as a title so it
      // appears as a tooltip when hovered.  This can help with debugging
      // without cluttering the on‑screen sprite.
      charDiv.title = displayDir;
      // Do not place any text inside the character div; the sprite itself
      // conveys the facing direction.
      charDiv.textContent = '';
  // Translate by half the sprite's width and height to centre it over the tile
  // and counter‑rotate so that the sprite remains upright even as the
  // grid is rotated.
  // Centre the sprite over the tile.  We do not rotate the sprite
  // itself here; the sprite orientation is controlled by swapping
  // images via getDisplayDirection().
  charDiv.style.transform = 'translate(-16px, -18px)';
}

/**
 * Move the character by the given axial delta.  If the destination is
 * within bounds the character's position is updated and the facing
 * direction is derived from the movement vector.  The character
 * direction is used to choose the correct sprite on the next render.
 *
 * @param {number} dq Delta in q
 * @param {number} dr Delta in r
 */
function moveCharacter(dq, dr) {
  const newQ = character.q + dq;
  const newR = character.r + dr;
    if (newQ >= 0 && newQ < GRID_SIZE && newR >= 0 && newR < GRID_SIZE) {
    character.q = newQ;
    character.r = newR;
    // Update the world facing direction based on movement.  The
    // directionVectors keys correspond exactly to the six axial
    // neighbours.
    if (dq === -1 && dr === 0) {
      character.facing = 'left';
    } else if (dq === 0 && dr === -1) {
      character.facing = 'left-up';
    } else if (dq === 1 && dr === -1) {
      character.facing = 'right-up';
    } else if (dq === 1 && dr === 0) {
      character.facing = 'right';
    } else if (dq === 0 && dr === 1) {
      character.facing = 'right-down';
    } else if (dq === -1 && dr === 1) {
      character.facing = 'left-down';
    }
    updateCharacter();
  }
}

// Initialise the grid and character
createTiles();
// Compute initial rotated positions and offsets, then draw the tiles
updateAllTiles();
// Draw the character at its starting location
updateCharacter();

// Listen for camera rotation keys.  Q rotates counter‑clockwise by 30°
// (turning the camera to the left) and E rotates clockwise by 30°
// (turning the camera to the right).  After rotating, the tiles and
// character are redrawn.
document.addEventListener('keydown', (event) => {
  if (event.key === 'q' || event.key === 'Q') {
    cameraAngle = (cameraAngle - 30) % 360;
    if (cameraAngle < 0) cameraAngle += 360;
    updateAllTiles();
    updateCharacter();
  } else if (event.key === 'e' || event.key === 'E') {
    cameraAngle = (cameraAngle + 30) % 360;
    updateAllTiles();
    updateCharacter();
  }
});
