"""
Simple Roguelite Proof‑of‑Concept
---------------------------------

This script implements a very small top‑down roguelite prototype using
the assets supplied in the accompanying ``assets`` folder.  It is **not**
the original 2000‑line game from the shanytopper/shany repository, but it
exercises all of the sprites so you can see them in action and verify
that the new graphics load correctly.  The player can walk around the
screen, shoot bullets, collect coins and potions, deploy bombs, and
fight two types of enemies (skeletons and goblins).  Each enemy uses
its respective sprite animations.  When an enemy dies it disappears;
when the player picks up a coin or potion it increments score or heals.

Controls:
    • Move with WASD or arrow keys.
    • Shoot with the space bar; bullets fire in the last moved direction.
    • Deploy a bomb with the ``B`` key (if you have any).

The game is deliberately simple and self‑contained so that it can be
tested in headless environments (e.g. with the dummy SDL video driver).
Run with ``python3 main.py`` to start.  To exit, close the window or
press ``ESC``.
"""

from __future__ import annotations
import os
import sys
import math
import random
import pygame
from typing import Dict, List, Tuple


###############################################################################
# Asset loading helpers
###############################################################################

ASSET_DIR = os.path.join(os.path.dirname(__file__), 'assets')

def load_hero_frames(path: str) -> Dict[int, List[pygame.Surface]]:
    """
    Load hero frames from a 4×4 spritesheet.  The sheet is assumed to
    contain four rows (up, down, left, right) and four columns (animation
    frames).  Frames are 32×32 pixels and will be scaled to 32×48 for
    better proportions.

    Returns a dictionary keyed by direction constant (0=up,1=down,2=left,3=right)
    mapping to lists of pygame.Surface frames.
    """
    sheet = pygame.image.load(path).convert_alpha()
    # compute frame size based on sheet dimensions
    sheet_width, sheet_height = sheet.get_size()
    tile_w = sheet_width // 4
    tile_h = sheet_height // 4
    frames: Dict[int, List[pygame.Surface]] = {0: [], 1: [], 2: [], 3: []}
    for row, dir_idx in enumerate([0, 1, 2, 3]):
        for col in range(4):
            frame = sheet.subsurface((col * tile_w, row * tile_h, tile_w, tile_h)).copy()
            # scale to 32×48 (keeping width but elongating height for humanoid proportions)
            frame = pygame.transform.scale(frame, (32, 48))
            frames[dir_idx].append(frame)
    return frames


def load_enemy_frames(directory: str) -> Dict[int, List[pygame.Surface]]:
    """
    Load enemy frames from a directory with files named
    ``jump_down (n).png``, ``jump_up (n).png`` and ``jump_right (n).png``
    where n runs from 1 through 4.  Left frames are generated by
    horizontally flipping the right frames.  Returns a dictionary mapping
    direction constants (0=up,1=down,2=left,3=right) to lists of frames.
    """
    directions = {0: 'jump_up', 1: 'jump_down', 3: 'jump_right'}
    frames: Dict[int, List[pygame.Surface]] = {0: [], 1: [], 2: [], 3: []}
    for dir_idx, name in directions.items():
        for i in range(1, 5):
            img_path = os.path.join(directory, f"{name} ({i}).png")
            img = pygame.image.load(img_path).convert_alpha()
            # scale to match hero size (32×48) if needed
            img = pygame.transform.scale(img, (32, 48))
            frames[dir_idx].append(img)
    # create left frames by flipping right frames
    frames[2] = [pygame.transform.flip(f, True, False) for f in frames[3]]
    return frames


def load_slime_frames(path: str) -> List[pygame.Surface]:
    """
    Load slime frames from a sprite sheet.  The sheet is 320×640 with 10
    columns and 20 rows of 32×32 frames (this matches the original game's
    assets).  We'll only use the first row of frames for walking animation.
    Returns a list of four frames scaled up to 32×32.
    """
    sheet = pygame.image.load(path).convert_alpha()
    frames: List[pygame.Surface] = []
    for col in range(4):
        frame = sheet.subsurface((col * 32, 0, 32, 32)).copy()
        frames.append(frame)
    return frames


def load_potion_images(path: str) -> List[pygame.Surface]:
    """
    Load the four potions from the horizontal strip.  Each potion is 16×16.
    We scale them up to 16×16 (no scaling) and return a list.
    """
    sheet = pygame.image.load(path).convert_alpha()
    frames: List[pygame.Surface] = []
    for i in range(4):
        frames.append(sheet.subsurface((i * 16, 0, 16, 16)).copy())
    return frames


def load_coin_frames(path: str) -> List[pygame.Surface]:
    """
    Load the 12 frames of the coin strip.  Each frame is 16×16.  Returns
    a list for coin animation.
    """
    sheet = pygame.image.load(path).convert_alpha()
    frames: List[pygame.Surface] = []
    for i in range(12):
        frames.append(sheet.subsurface((i * 16, 0, 16, 16)).copy())
    return frames


###############################################################################
# Entity classes
###############################################################################

# Direction constants
UP, DOWN, LEFT, RIGHT = 0, 1, 2, 3


class Player:
    def __init__(self, x: float, y: float, frames: Dict[int, List[pygame.Surface]]):
        self.x = x
        self.y = y
        self.width = 32
        self.height = 48
        self.frames = frames
        self.direction = DOWN  # facing down initially
        self.anim_index = 0
        self.anim_timer = 0.0
        self.anim_speed = 0.12  # seconds per frame
        self.speed = 160.0
        self.health = 100
        self.max_health = 100
        self.coins = 0
        self.potions = 0
        self.bombs = 1
        # bullets fired in the last direction
        self.last_move_dir = DOWN

    @property
    def rect(self) -> pygame.Rect:
        return pygame.Rect(int(self.x), int(self.y), self.width, self.height)

    def update(self, dt: float, keys: pygame.key.ScancodeWrapper):
        # Movement
        dx = dy = 0.0
        moving = False
        if keys[pygame.K_w] or keys[pygame.K_UP]:
            dy -= 1
            self.last_move_dir = UP
            moving = True
        if keys[pygame.K_s] or keys[pygame.K_DOWN]:
            dy += 1
            self.last_move_dir = DOWN
            moving = True
        if keys[pygame.K_a] or keys[pygame.K_LEFT]:
            dx -= 1
            self.last_move_dir = LEFT
            moving = True
        if keys[pygame.K_d] or keys[pygame.K_RIGHT]:
            dx += 1
            self.last_move_dir = RIGHT
            moving = True
        # normalize movement
        if dx != 0 or dy != 0:
            length = math.hypot(dx, dy)
            dx /= length
            dy /= length
            self.direction = self.last_move_dir
        # update position
        self.x += dx * self.speed * dt
        self.y += dy * self.speed * dt
        # constrain to screen
        self.x = max(0, min(self.x, 800 - self.width))
        self.y = max(0, min(self.y, 600 - self.height))
        # update animation
        self.anim_timer += dt
        if self.anim_timer >= self.anim_speed:
            self.anim_timer -= self.anim_speed
            self.anim_index = (self.anim_index + 1) % len(self.frames[self.direction])

    def draw(self, surface: pygame.Surface):
        frame = self.frames[self.direction][self.anim_index]
        surface.blit(frame, (self.x, self.y))


class Bullet:
    def __init__(self, x: float, y: float, direction: int):
        self.pos = pygame.Vector2(x, y)
        speed = 400.0
        if direction == UP:
            self.vel = pygame.Vector2(0, -speed)
        elif direction == DOWN:
            self.vel = pygame.Vector2(0, speed)
        elif direction == LEFT:
            self.vel = pygame.Vector2(-speed, 0)
        else:
            self.vel = pygame.Vector2(speed, 0)
        self.alive = True

    def update(self, dt: float):
        self.pos += self.vel * dt
        if (self.pos.x < 0 or self.pos.x > 800 or
            self.pos.y < 0 or self.pos.y > 600):
            self.alive = False

    def draw(self, surface: pygame.Surface):
        pygame.draw.circle(surface, (255, 215, 0), (int(self.pos.x), int(self.pos.y)), 3)


class Bomb:
    def __init__(self, x: float, y: float):
        self.pos = pygame.Vector2(x, y)
        self.fuse = 1.0  # seconds until explosion
        self.radius = 80.0
        self.exploded = False

    def update(self, dt: float):
        if not self.exploded:
            self.fuse -= dt
            if self.fuse <= 0:
                self.exploded = True

    def draw(self, surface: pygame.Surface, bomb_img: pygame.Surface):
        if not self.exploded:
            # centre bomb image on position
            rect = bomb_img.get_rect(center=(int(self.pos.x), int(self.pos.y)))
            surface.blit(bomb_img, rect)
        else:
            # draw explosion circle
            pygame.draw.circle(surface, (255, 128, 0), (int(self.pos.x), int(self.pos.y)), int(self.radius), 2)


class Potion:
    def __init__(self, x: float, y: float, img: pygame.Surface):
        self.pos = pygame.Vector2(x, y)
        self.img = img
        self.rect = img.get_rect(center=(int(x), int(y)))

    def draw(self, surface: pygame.Surface):
        surface.blit(self.img, self.rect)


class Coin:
    def __init__(self, x: float, y: float, frames: List[pygame.Surface]):
        self.pos = pygame.Vector2(x, y)
        self.frames = frames
        self.anim_index = 0
        self.anim_timer = 0.0
        self.anim_speed = 0.08
        self.rect = frames[0].get_rect(center=(int(x), int(y)))

    def update(self, dt: float):
        self.anim_timer += dt
        if self.anim_timer >= self.anim_speed:
            self.anim_timer -= self.anim_speed
            self.anim_index = (self.anim_index + 1) % len(self.frames)

    def draw(self, surface: pygame.Surface):
        img = self.frames[self.anim_index]
        # centre coin image on position
        rect = img.get_rect(center=(int(self.pos.x), int(self.pos.y)))
        surface.blit(img, rect)


class Enemy:
    def __init__(self, x: float, y: float, frames: Dict[int, List[pygame.Surface]]):
        self.pos = pygame.Vector2(x, y)
        self.width = 32
        self.height = 48
        self.frames = frames
        self.direction = DOWN
        self.anim_index = 0
        self.anim_timer = 0.0
        self.anim_speed = 0.15
        self.speed = 70.0
        self.health = 40
        self.alive = True

    @property
    def rect(self) -> pygame.Rect:
        return pygame.Rect(int(self.pos.x), int(self.pos.y), self.width, self.height)

    def update(self, dt: float, player: Player):
        if not self.alive:
            return
        # Move towards player
        direction_vector = pygame.Vector2(player.x - self.pos.x, player.y - self.pos.y)
        if direction_vector.length() != 0:
            direction_vector = direction_vector.normalize()
            self.pos += direction_vector * self.speed * dt
            # determine facing direction for animation
            if abs(direction_vector.x) > abs(direction_vector.y):
                self.direction = RIGHT if direction_vector.x > 0 else LEFT
            else:
                self.direction = DOWN if direction_vector.y > 0 else UP
        # update animation
        self.anim_timer += dt
        if self.anim_timer >= self.anim_speed:
            self.anim_timer -= self.anim_speed
            self.anim_index = (self.anim_index + 1) % len(self.frames[self.direction])

    def damage(self, amount: int):
        self.health -= amount
        if self.health <= 0:
            self.alive = False

    def draw(self, surface: pygame.Surface):
        if not self.alive:
            return
        frame = self.frames[self.direction][self.anim_index]
        surface.blit(frame, (self.pos.x, self.pos.y))


###############################################################################
# Game logic
###############################################################################

def run_game() -> None:
    pygame.init()
    screen = pygame.display.set_mode((800, 600))
    pygame.display.set_caption('Roguelite POC')
    clock = pygame.time.Clock()

    # Load assets
    hero_frames = load_hero_frames(os.path.join(ASSET_DIR, 'hero.png'))
    skeleton_frames = load_enemy_frames(os.path.join(ASSET_DIR, 'skeleton'))
    goblin_frames = load_enemy_frames(os.path.join(ASSET_DIR, 'monster'))
    slime_frames = load_slime_frames(os.path.join(ASSET_DIR, 'slime_spritesheet.png'))
    potion_images = load_potion_images(os.path.join(ASSET_DIR, 'potion_set_16x16.png'))
    coin_frames = load_coin_frames(os.path.join(ASSET_DIR, 'coin_strip.png'))
    bomb_img = pygame.image.load(os.path.join(ASSET_DIR, 'bomb.png')).convert_alpha()

    # Create objects
    player = Player(400.0, 300.0, hero_frames)
    bullets: List[Bullet] = []
    bombs: List[Bomb] = []
    coins: List[Coin] = []
    potions: List[Potion] = []
    enemies: List[Enemy] = []

    # Spawn initial items and enemies
    def spawn_enemy() -> None:
        # choose skeleton or goblin randomly
        f = skeleton_frames if random.random() < 0.5 else goblin_frames
        x = random.randint(50, 750)
        y = random.randint(50, 550)
        enemies.append(Enemy(x, y, f))

    def spawn_coin() -> None:
        x = random.randint(20, 780)
        y = random.randint(20, 580)
        coins.append(Coin(x, y, coin_frames))

    def spawn_potion() -> None:
        x = random.randint(20, 780)
        y = random.randint(20, 580)
        img = random.choice(potion_images)
        potions.append(Potion(x, y, img))

    for _ in range(3):
        spawn_enemy()
        spawn_coin()
        spawn_potion()

    running = True
    bomb_cooldown = 0.0
    while running:
        dt = clock.tick(60) / 1000.0  # delta time in seconds
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
                elif event.key == pygame.K_SPACE:
                    # shoot bullet
                    center_x = player.x + player.width / 2
                    center_y = player.y + player.height / 2
                    bullets.append(Bullet(center_x, center_y, player.last_move_dir))
                elif event.key == pygame.K_b:
                    # deploy bomb if available and cooldown expired
                    if player.bombs > 0 and bomb_cooldown <= 0.0:
                        center = pygame.Vector2(player.x + player.width / 2, player.y + player.height / 2)
                        bombs.append(Bomb(center.x, center.y))
                        player.bombs -= 1
                        bomb_cooldown = 0.5  # half second before next bomb

        keys = pygame.key.get_pressed()
        player.update(dt, keys)
        for bullet in bullets:
            bullet.update(dt)
        for bomb in bombs:
            bomb.update(dt)
        for coin in coins:
            coin.update(dt)
        for enemy in enemies:
            enemy.update(dt, player)
        # remove dead bullets
        bullets = [b for b in bullets if b.alive]
        # handle bullet/enemy collisions
        for bullet in bullets:
            for enemy in enemies:
                if enemy.alive and enemy.rect.collidepoint(bullet.pos.x, bullet.pos.y):
                    enemy.damage(10)
                    bullet.alive = False
                    break
        # handle bomb explosions
        for bomb in bombs:
            if bomb.exploded and bomb.fuse < 0:
                continue
            if bomb.exploded:
                # damage enemies within radius
                for enemy in enemies:
                    if enemy.alive and enemy.pos.distance_to(bomb.pos) <= bomb.radius:
                        enemy.damage(30)
                # mark as finished to avoid repeated damage
                bomb.fuse = -1.0
        # remove finished bombs
        bombs = [b for b in bombs if not (b.exploded and b.fuse < 0)]
        # handle player/enemy collision (damage player)
        for enemy in enemies:
            if enemy.alive and player.rect.colliderect(enemy.rect):
                player.health -= 20 * dt
                if player.health <= 0:
                    running = False
        # handle player/coin collision
        for coin in coins[:]:
            if player.rect.colliderect(coin.rect):
                player.coins += 1
                coins.remove(coin)
                spawn_coin()
        # handle player/potion collision
        for potion in potions[:]:
            if player.rect.colliderect(potion.rect):
                player.health = min(player.max_health, player.health + 25)
                potions.remove(potion)
                spawn_potion()
        # occasionally spawn new enemies/items
        if random.random() < 0.01:
            spawn_enemy()
        if random.random() < 0.02:
            spawn_coin()
        if random.random() < 0.01:
            spawn_potion()
        # reduce bomb cooldown
        if bomb_cooldown > 0:
            bomb_cooldown -= dt
        # drawing
        screen.fill((27, 27, 43))
        # draw items
        for coin in coins:
            coin.draw(screen)
        for potion in potions:
            potion.draw(screen)
        # draw bombs
        for bomb in bombs:
            bomb.draw(screen, bomb_img)
        # draw enemies
        for enemy in enemies:
            enemy.draw(screen)
        # draw player
        player.draw(screen)
        # draw UI (health and coins)
        font = pygame.font.SysFont('Arial', 18)
        health_text = font.render(f"Health: {int(player.health)}", True, (255, 255, 255))
        coin_text = font.render(f"Coins: {player.coins}", True, (255, 215, 0))
        bomb_text = font.render(f"Bombs: {player.bombs}", True, (200, 200, 200))
        screen.blit(health_text, (10, 10))
        screen.blit(coin_text, (10, 30))
        screen.blit(bomb_text, (10, 50))
        pygame.display.flip()
    pygame.quit()


if __name__ == '__main__':
    run_game()